### ISSUE TITLE
Feature request: crypto_pwhash

### ISSUE THREAD

**Issue by maximkott** [serenity-kit/react-native-libsodium#49]
Are you considering adding `crypto_pwhash` in the future?

**Comment by maximkott** [comment]
I see that you had this binding and decided to remove it in this commit: https://github.com/serenity-kit/react-native-libsodium/commit/d7534e1a6ac0767846569a7b78ddc01b5224ea90

Could you share the reason for this? Is there a better way to do this? Thanks

**Comment by nikgraf** [comment]
@maximkott I'm happy to bring them back. The reason for removing them was that there was a bug in there, we didn't need the function in our product anymore and we were under time pressure.

Would you be interested in restoring them as PR. I can take a look then.

**Comment by maximkott** [comment]
@nikgraf Thank you for the offer, this would be really great.

I've created this PR https://github.com/serenity-kit/react-native-libsodium/pull/50 based on the removed commit. The only thing I've slightly adjusted was the test case, since you've restructured all the tests.

I couldn't start the react native app, something is misconfigured on my device.

Let me know if I can support you on this any further. I'd love to help out, event though it looks black magic 😆

**Comment by connoremma** [comment]
Need this as well – trying to fix https://github.com/TipLink/tiplink-api for them

**Comment by nikgraf** [comment]
sorry, very busy week with a Security audit happening. Next or in two weeks latests I should have time for it.

**Comment by nikgraf** [comment]
added and released it, let me know if it works as expected

P.S: please consider sponsoring https://github.com/sponsors/nikgraf (adding it and fixing loading issues connected to it were all done in my spare time)

**Comment by maximkott** [comment]
@nikgraf Thanks a lot for this update 👏 I wasn't able to test it yet. 

I'll get back to you 💯
